<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="POL-6MXJDB3" failures="1" tests="3" name="com.dydko.basic.reporterlog.EmailReport" time="0.100" errors="0" timestamp="2024-02-11T09:05:23 CET" skipped="1">
  <testcase classname="com.dydko.basic.reporterlog.EmailReport" name="failTest" time="0.012">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at com.dydko.basic.reporterlog.EmailReport.failTest(EmailReport.java:39)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
    <system-out>
      <![CDATA[test10: 10
test10: 20
test10: 30
test10: 40]]>
    </system-out>
  </testcase> <!-- failTest -->
  <testcase classname="com.dydko.basic.reporterlog.EmailReport" name="passTest" time="0.083">
    <system-out>
      <![CDATA[test1: 1
test1: 2
test1: 3
test1: 4]]>
    </system-out>
  </testcase> <!-- passTest -->
  <testcase classname="com.dydko.basic.reporterlog.EmailReport" name="skipTest" time="0.005">
    <skipped/>
    <system-out>
      <![CDATA[test100: 100
test100: 200
test100: 300
test100: 400]]>
    </system-out>
  </testcase> <!-- skipTest -->
  <system-out>
    <![CDATA[test10: 10
test100: 100
test10: 20
test100: 200
test10: 30
test100: 300
test100: 400
test10: 40
test1: 1
test1: 2
test1: 3
test1: 4]]>
  </system-out>
</testsuite> <!-- com.dydko.basic.reporterlog.EmailReport -->
